config/routes.rb
Rails.application.routes.draw do
  root to: 'records#index'
  resources:records
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @records = Record.all
  end

  def show
  end

  def new
    @record = Record.new
  end

  def create
    record = Record.new(record_params)
    record.save
    redirect_to records_url, notice: "コーヒー「#(record.name)」を登録いたしました。"
  
    def edit
  end
end

private

  def record_params
    params.require(:record).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | My Coffee App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
  .app-title.navbar.expand-md.navbar-light.bg-light
    .navbar-brand Coffee Record
  .container
    = yield

app/views/records/edit.html.slim
h1 Records#edit
p Find me in app/views/records/edit.html.slim

app/views/records/index.html.slim
h1 登録しているコーヒーの一覧
= link_to  "コーヒー登録",new_record_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
    thead.thead-default
        tr
            th = Record.human_attribute_name(:name)
            th = Record.human_attribute_name(:created_at)
        tbody
            - @records.each do |record|
            tr
                td = record.name
                td = record.created_at

app/views/records/new.html.slim
h1 コーヒーの登録

.nav.justify-content-end
    = link_to "トップに戻る", records_path, class: 'nav-link'

= form_with model: @record, local: true do |f|
    .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control', id: 'task_name'
    .form-group
        = f.label :description
        = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
    = f.submit nil, class: 'btn btn-primary'

app/views/records/show.html.slim
h1 Records#show
p Find me in app/views/records/show.html.slim